_core_utils:
  - coreutils
  - htop
  - watch

_dev_tools:
  - gh
  - neovim
  - tmux
  - ranger
  - ripgrep
  - fd
  - bat
  - fzf
  - exa
  - jq
  - yq

_extras:
  - tldr
  - figlet
  - lolcat
  - azure-cli

brew_packages: "{{ _core_utils + _dev_tools + _extras }}"
