- name: Completely setting up a linux machine
  hosts: localhost

  roles:
    - role: arch
      when: ansible_os_family == "Archlinux"
    # - role: debian
    #   when: ansible_os_family == "Debian"
    # - role: common

