---
- hosts: localhost
  connection: local
  vars:
    _gui: False

  tasks:
    - assert:
        that: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

    - import_role:
        name: ubuntu
