- name: "Install GNU stow"
  ansible.builtin.package:
    name: stow
    state: present

- name: Cloning dotfile repo
  ansible.builtin.git:
    repo: git@github.com:erietz/.dotfiles.git
    dest: "{{ _dotfiles_dir }}"

- name: Symlink files using stow
  command: ./install.sh
  args:
    chdir: "{{ _dotfiles_dir }}" 
  register: output
  changed_when: output.stdout != ""
