- name: "git clone {{_suckless_dwm_dir}}"
  ansible.builtin.git:
    repo: https://github.com:erietz/dwm
    dest: "{{_suckless_dwm_dir}}"

- name: sudo make install dwm
  make:
    chdir: "{{_suckless_dwm_dir}}"
    target: install
  become: yes


- name: "git clone {{_suckless_slstatus_dir}}"
  ansible.builtin.git:
    repo: https://github.com:erietz/slstatus
    dest: "{{_suckless_slstatus_dir}}"

- name: sudo make install slstatus
  make:
    chdir: "{{_suckless_slstatus_dir}}"
    target: install
  become: yes


- name: "git clone {{_suckless_st_dir}}"
  ansible.builtin.git:
    repo: https://github.com:erietz/st
    dest: "{{ _suckless_st_dir }}"

- name: sudo make install slstatus
  make:
    chdir: "{{_suckless_st_dir}}"
    target: install
  become: yes
