_neovim_dependencies:
  # TODO: install miniconda and get pynvim dependency installed
  - gcc       # treesitter
  # TODO: install nvm
  - nodejs    # coc
  - npm       # coc
  - fzf
  - ripgrep
  - fd-find
  - bat
