- name: Installing brew TUI packages
  community.general.homebrew:
    name: "{{ brew_packages }}"
    state: present

- name: Installing brew GUI packages
  community.general.homebrew_cask:
    name: "{{ brew_cask_packages }}"
    state: present
