- name: Full system upgrade
  community.general.homebrew:
    update_homebrew: yes
    upgrade_all: yes

- import_tasks: zsh_plugins.yml
  tags: zsh

- import_tasks: ./tasks/homebrew.yml
  tags: packages

- import_tasks: dotfiles.yml
  tags: dotfiles

- import_tasks: ./tasks/nvim_lsp.yml
  tags: lsp

- import_tasks: ./tasks/yabai.yml
  tags: yabai
