- name: Full system upgrade
  community.general.homebrew:
    update_homebrew: yes
    upgrade_all: yes

- import_tasks: zsh_plugins.yml
- import_tasks: dotfiles.yml
- import_tasks: ./tasks/homebrew.yml
- import_tasks: ./tasks/nvim_lsp.yml
