- name: conda install python-lsp-server
  shell: |
    source {{ _miniconda_dir }}/etc/profile.d/conda.sh
    conda install python-lsp-server

- name: conda install nodejs
  shell: |
    source {{ _miniconda_dir }}/etc/profile.d/conda.sh
    conda install nodejs

- name: npm install language servers for html, css, and typescript
  shell: |
    source {{ _miniconda_dir }}/etc/profile.d/conda.sh
    npm install -g ts-server vscode-langservers-extracted
