- name: Check if miniconda is installed
  stat: path={{ _miniconda_dir }}/bin/conda
  register: bin_conda
  changed_when: bin_conda.stat.exists == False

- name: Download miniconda installer
  become: False
  get_url:
    url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    dest: /tmp/install-miniconda.sh
    checksum: sha256:78f39f9bae971ec1ae7969f0516017f2413f17796670f7040725dd83fcff5689
    mode: 0755
  register: miniconda_downloaded
  when: bin_conda.stat.exists == False

- name: Run miniconda installer
  become: False
  ansible.builtin.command:
    argv:
      - /tmp/install-miniconda.sh
      - -b
      - -p
      - "{{ _miniconda_dir }}"
