- name: Installing neovim
  become: yes
  community.general.pacman:
    name: neovim
    state: present

- name: Installing programs used by neovim config
  become: yes
  community.general.pacman:
    name: "{{ _neovim_dependencies }}"
    state: present
