- name: Installing zsh
  become: yes
  community.general.pacman:
    name:
      - zsh
      - inetutils   # because my config requires `hostname`
    state: present

- name: Change shell to zsh
  become: yes
  shell: chsh -s $(which zsh)

- name: Create _plugin_dir if it doesn't exist
  file:
    dest: "{{ _plugin_dir }}"
    state: directory

- name: Cloning git prompt
  get_url:
    url: https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh
    dest: "{{ _plugin_dir }}/git-prompt.sh"

- name: Cloning zsh plugins
  ansible.builtin.git:
    repo: https://github.com/zsh-users/{{ item }}.git
    dest: "{{ _plugin_dir }}/{{ item }}"
  with_items:
    - zsh-syntax-highlighting
    - zsh-completions
    - zsh-autosuggestions
