- name: Installing zsh
  become: True
  community.general.pacman:
    name:
      - zsh
      - inetutils   # because my config requires `hostname`
    state: present

- name: Change shell to zsh
  command: usermod --shell /bin/zsh "{{ lookup('env', 'USER') }}"
  become: true
  changed_when: false

- import_tasks: zsh_plugins.yml
