_pacman_packages_tui:
  - stow
  - neovim
  - which
  - tmux
  - ranger
  - jq
  - yq
  - tldr
  - github-cli
  - python-pip

_pacman_packages_gui:
  - alacritty
  - ttf-jetbrains-mono
  - ttf-ubuntu-font-family
  - firefox
  - discord
  - zathura
