_pacman_packages_tui:
  - which
  - tmux
  - ranger
  - jq
  - yq
  - tldr
  - github-cli
  - python-pip

_pacman_packages_gui:
  - alacritty
  - ttf-jetbrains-mono
  - ttf-ubuntu-font-family
  - firefox
  - discord
  - zathura

_neovim_dependencies:
  # TODO: install miniconda and get pynvim dependency installed
  - gcc       # treesitter
  # TODO: install nvm
  - nodejs    # coc
  - npm       # coc
  - fzf
  - ripgrep
  - fd
  - bat
