- name: Installing apt TUI package
  become: True
  apt:
    pkg:
      - build-essential
      - sudo
      - stow
      - neovim
      - tmux
      - ranger
      - jq
      # - yq  # this is not correct in apt repos
      - tldr
      - gh
      # - python-pip-whl
      - python3-pip
      - bat
      - fd-find
      - ripgrep
      - fzf


# GitHub actions must not use /usr/bin
- name: Aliasing batcat
  file:
    src: /bin/batcat
    dest: "{{ lookup('env', 'HOME') }}/.local/bin/bat"
    state: link

- name: Aliasing fd-find
  file:
    src: /bin/fdfind
    dest: "{{ lookup('env', 'HOME') }}/.local/bin/fd"
    state: link


- name: Installing dwm prerequisites
  when: _gui
  become: True
  apt:
    pkg:

      # dwm
      - build-essential
      - libx11-dev
      - libxft-dev
      - libxinerama-dev
      - libfreetype6-dev
      - libfontconfig1-dev
      - xinit
      - xterm

- name: Installing apt GUI packages
  when: _gui
  become: True
  apt:
    pkg:
      - dmenu
      - rofi
      - firefox
      # - discord
      - zathura
      - clipit
      - nm-tray
      - xautolock
      - nitrogen
      - xfce4-power-manager
      - pasystray
      - breeze-cursor-theme
      - libnotify-bin
