- name: Installing apt TUI package
  become: True
  apt:
    pkg:
      - neovim
      - tmux
      - ranger
      - jq
      # - yq  # this is not correct in apt repos
      - tldr
      - gh
      # - python-pip-whl
      - python3-pip
      - bat
      - fd-find

# GitHub actions must not use /usr/bin
# - name: Aliasing batcat
#   file:
#     src: /usr/bin/batcat
#     dest: "{{ lookup('env', 'HOME') }}/.local/bin/bat"
#     state: link

# - name: Aliasing fd-find
#   file:
#     src: /usr/bin/fdfind
#     dest: "{{ lookup('env', 'HOME') }}/.local/bin/fd"
#     state: link


- name: Installing pacman GUI packages
  when: _gui
  become: True
  apt:
    pkg:
      # - alacritty
      # - ttf-jetbrains-mono
      # - ttf-ubuntu-font-family
      - firefox
      - discord
      - zathura

