- name: Full system upgrade
  become: true
  apt:
    upgrade: yes
    update_cache: yes

- import_tasks: ./apt.yml
  tags: packages

# - import_tasks: ./tasks/miniconda.yml

- import_tasks: ./tasks/zsh.yml
  tags: zsh

- import_tasks: dotfiles.yml
  tags: dotfiles

- import_tasks: ./tasks/neovim.yml

- import_tasks: suckless.yml

# - import_tasks: ./tasks/i3.yml
#   when: _gui
