- name: Full system upgrade
  become: true
  apt:
    upgrade: yes
    update_cache: yes

- import_tasks: ./apt.yml
  tags: packages

- import_tasks: miniconda.yml
  tags: miniconda

- import_tasks: ./tasks/zsh.yml
  tags: zsh

- import_tasks: dotfiles.yml
  tags: dotfiles

- import_tasks: suckless.yml
  when: _gui
  tags: suckless
