- name: Installing neovim
  become: True
  apt:
    name: neovim
    state: present

- name: Installing programs used by neovim config
  become: True
  apt:
    name: "{{ _neovim_dependencies }}"
    state: present

- name: Running pip install pynvim
  command: pip install pynvim

