- name: Installing zsh
  become: true
  apt:
    name: zsh
    state: present

- name: Change shell to zsh
  become: true
  command: usermod --shell /bin/zsh "{{ lookup('env', 'USER') }}"
  changed_when: false

- import_tasks: zsh_plugins.yml
