- name: Full system upgrade
  become: yes
  community.general.pacman:
    update_cache: yes
    upgrade: yes

- import_tasks: ./tasks/zsh.yml
  vars:
    plugin_dir: "{{ lookup('env', 'HOME') }}/.config/ewr-plugins"

- import_tasks: ./tasks/dotfiles.yml
  vars:
    dotfiles_dir: "{{ lookup('env', 'HOME') }}/.dotfiles"

- import_tasks: ./tasks/neovim.yml

- import_tasks: ./tasks/i3.yml
