name: Dotfiles on macOS

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/macos.yaml"
      - "macos.ymlx"
      - "roles/macos/**"
      - "group_vars/**"
      - "tasks/**"
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/macos.yaml"
      - "macos.ymlx"
      - "roles/macos/**"
      - "group_vars/**"
      - "tasks/**"

jobs:

  install_macos:
    runs-on: macos-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install Ansible
        run: brew install ansible

      - name: Ansible Playbook -> Macos
        run: ansible-playbook -vv macosx.yml
