name: Dotfiles on Manjaro

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/manjaro.yaml"
      - "manjaro.yml"
      - "roles/manjaro/**"
      - "group_vars/**"
      - "tasks/**"
      - "test/manjaro/Dockerfile"
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/manjaro.yaml"
      - "ubuntu.yml"
      - "roles/manjaro/**"
      - "group_vars/**"
      - "tasks/**"
      - "test/manjaro/Dockerfile"

jobs:

  install_manjaro:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install make
        run: sudo apt install make

      - name: docker build manjaro image
        run: make build-manjaro
