name: Dotfiles on Manjaro

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/manjaro.yaml"
      - "manjaro.yml"
      - "roles/manjaro/**"
      - "group_vars/**"
      - "tasks/**"
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/manjaro.yaml"
      - "ubuntu.yml"
      - "roles/manjaro/**"
      - "group_vars/**"
      - "tasks/**"

jobs:

  install_manjaro:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: docker build manjaro image
        run: |
          docker build --rm -t "manjaro:dotfiles" -f ./test/manjaro/Dockerfile ./

      - name: docker run ansible playbook
        run: |
          echo "secret_pw" | docker run --rm -i "manjaro:dotfiles"
